import { Amplify } from 'aws-amplify';
// amplify_outputs.json lives at the project root and is generated by:
//   npx ampx generate outputs --branch main --app-id d2abcyagvq3j4o --out-dir .
import outputs from '../../amplify_outputs.json';

Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0]);
