import { Amplify } from 'aws-amplify';
// amplify_outputs.json is generated by `ampx sandbox` or `ampx pipeline-deploy`
// from the invoicesandexpensesmobile project. Copy it to src/amplify_outputs.json.
// See README.md for full setup instructions.
import outputs from '../amplify_outputs.json';

Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0]);
